from .storyah_save_audio import NODE_CLASS_MAPPINGS as _AUDIO_MAP, NODE_DISPLAY_NAME_MAPPINGS as _AUDIO_DISPLAY
from .storyah_save_video import NODE_CLASS_MAPPINGS as _VIDEO_MAP, NODE_DISPLAY_NAME_MAPPINGS as _VIDEO_DISPLAY
from .storyah_musetalk_save import NODE_CLASS_MAPPINGS as _MT_MAP, NODE_DISPLAY_NAME_MAPPINGS as _MT_DISPLAY
from .storyah_musetalk_bridge import NODE_CLASS_MAPPINGS as _MTB_MAP, NODE_DISPLAY_NAME_MAPPINGS as _MTB_DISPLAY

NODE_CLASS_MAPPINGS = {**_AUDIO_MAP, **_VIDEO_MAP, **_MT_MAP, **_MTB_MAP}
NODE_DISPLAY_NAME_MAPPINGS = {**_AUDIO_DISPLAY, **_VIDEO_DISPLAY, **_MT_DISPLAY, **_MTB_DISPLAY}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
